- CHANGELOG.md
- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
- spec/fixtures/BananaLib.podspec
> [Push] Lint as framework automatically.

- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
> [Push] Update the master repo both before and after pushing

- CHANGELOG.md
- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/3855.
> [Push] Propagate --allow-warnings to the trunk server

- CHANGELOG.md
- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
> [Push] Run `pod setup` if needed

- lib/pod/command/trunk/delete.rb
> Suggest deprecate and discourage deleting pod versions.

- CHANGELOG.md
- lib/pod/command/trunk.rb
- lib/pod/command/trunk/delete.rb
- lib/pod/command/trunk/deprecate.rb
- lib/pod/command/trunk/push.rb
- spec/command/trunk/delete_spec.rb
- spec/command/trunk/deprecate_spec.rb
- spec/spec_helper.rb
> Add support for deleting and deprecating pods

- CHANGELOG.md
- lib/pod/command/trunk.rb
- lib/pod/command/trunk/deprecate.rb
- spec/command/trunk/deprecate_spec.rb
- spec/spec_helper.rb
> [Deprecate] Send a body with the patch request

- CHANGELOG.md
- Gemfile.lock
- lib/pod/command/trunk/push.rb
- lib/pod/command/trunk/register.rb
- spec/command/trunk/push_spec.rb
> compatibility with CocoaPods 1.0.0.beta.7+

- CHANGELOG.md
- lib/pod/command/trunk/push.rb
> [Push] Include error when saying unable to load spec

- lib/pod/command/trunk/add_owner.rb
- lib/pod/command/trunk/delete.rb
- lib/pod/command/trunk/deprecate.rb
- lib/pod/command/trunk/info.rb
- lib/pod/command/trunk/me.rb
- lib/pod/command/trunk/push.rb
- lib/pod/command/trunk/register.rb
- lib/pod/command/trunk/remove_owner.rb
I _think_ I got this right, seems to be only initial commands and the ones added in `1.0.0.beta.1`.
https://github.com/CocoaPods/guides.cocoapods.org/pull/115
> [Docs] CocoaPods availability

- lib/pod/command/trunk.rb
https://github.com/CocoaPods/CocoaPods/issues/5372
> [Errors] Fix typo

- Gemfile
https://github.com/CocoaPods/Rainforest/issues/63
> Fix json gem with Ruby 2.2

- .travis.yml
Took the CP one, and tried to re-apply it here
> Use a version of the CocoaPods travis repo

- CHANGELOG.md
- Gemfile.lock
- lib/pod/command/trunk/push.rb
> [Push] Maintain backwards compatibility with old validators

- CHANGELOG.md
- lib/pod/command/trunk/push.rb
fixes https://github.com/CocoaPods/CocoaPods/issues/6209
> Fix backwards compatiblity with CocoaPods <= 1.1.0

- CHANGELOG.md
- Gemfile.lock
- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
Related to https://github.com/CocoaPods/CocoaPods/pull/6420
> Add skip validation option to trunk push

- CHANGELOG.md
- Gemfile.lock
- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
Also fixes tests by bumping to latest SHA of CocoaPods
> Add skip test option to trunk push

- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/7683
Continuation of https://github.com/CocoaPods/CocoaPods/pull/7959
> Add --use-modular-headers flag to `push`

- lib/pod/command/trunk/push.rb
for https://github.com/CocoaPods/CocoaPods/issues/8236
> make push help log more precise

- CHANGELOG.md
- lib/pod/command/trunk/push.rb
- spec/command/trunk/push_spec.rb
Fix https://github.com/CocoaPods/CocoaPods/issues/9497
> Add --synchronous option to pod trunk push
